sqs:
  queue:
    request: https://sqs.us-east-1.amazonaws.com/620247385745/iaas-request-sqs
    response: https://sqs.us-east-1.amazonaws.com/620247385745/iaas-response-sqs

s3:
  bucket:
    request: iaas-request-bucket
    response: iaas-response-bucket

login:
  access:
  secret:
  keypair: 546-KeyPair
  sg: sg-0cc021372a3cb502f

ami:
  id: ami-0b3af756c259667df

ec2:
  max-instances: 19