sqs:
  queue:
    request: https://sqs.us-east-1.amazonaws.com/867386276772/openstack-request-sqs
    response: https://sqs.us-east-1.amazonaws.com/867386276772/openstack-response-sqs

s3:
  bucket:
    request: openstack-546-request-bucket
    response: openstack-546-response-bucket

login:
  access:
  secret:
  keypair: 546-KeyPair
  sg: sg-025612337724c49d7

ami:
  id: ami-084125967033d4294

ec2:
  max-instances: 19