sqs:
  queue:
    request: https://sqs.us-west-1.amazonaws.com/141013654556/cloud-computing-project1-request-queue
    response: https://sqs.us-west-1.amazonaws.com/141013654556/cloud-computing-project1-response-queue

s3:
  bucket:
    request: cse546-project1-image-bucket
    response: cse546-project1-results-bucket

login:
  access: AKIASBVIRTQOAE3QVKRE
  secret: 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
  keypair: 546-keypair
  sg: sg-070982a4b1f57489c

ami:
  id: ami-032cb4caa5b1db6ce

ec2:
  max-instances: 19